08/14/2024 18:27:08 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: no
{'rescale_betas_zero_snr', 'clip_sample_range', 'variance_type', 'sample_max_value', 'dynamic_thresholding_ratio', 'thresholding'} was not found in config. Values will be initialized to default values.
An error occurred while trying to fetch SG161222/Realistic_Vision_V6.0_B1_noVAE: SG161222/Realistic_Vision_V6.0_B1_noVAE does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
{'use_post_quant_conv', 'shift_factor', 'latents_mean', 'mid_block_add_attention', 'latents_std', 'use_quant_conv'} was not found in config. Values will be initialized to default values.
An error occurred while trying to fetch SG161222/Realistic_Vision_V6.0_B1_noVAE: SG161222/Realistic_Vision_V6.0_B1_noVAE does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Traceback (most recent call last):
  File "/lustre/home/vfourel/FaceGPT/Champ/Guidance/train_text_to_image.py", line 1177, in <module>
    main(config)
  File "/lustre/home/vfourel/FaceGPT/Champ/Guidance/train_text_to_image.py", line 848, in main
    accelerator.init_trackers(args.tracker_project_name, tracker_config)
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/accelerate/accelerator.py", line 602, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/accelerate/accelerator.py", line 2205, in init_trackers
    tracker.store_init_configuration(config)
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/accelerate/tracking.py", line 84, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/accelerate/tracking.py", line 212, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 330, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/home/vfourel/miniconda3/envs/champv2/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 318, in hparams
    raise ValueError(
ValueError: value should be one of int, float, str, bool, or torch.Tensor